### ISSUE TITLE
How to train a new model from scratch/ continue training

### ISSUE THREAD

**Issue by Jbru18** [connorcoley/scscore#8]
HI Connor,

From your previous post I learned that a model can be retrained. I am unclear, however, on how to train a model from scratch or expand (augment the existing) training. Can you please explain a little further.

I am also interested in using different fingerprints and /or similarity criteria. I was not clear what similarity criteria you used for comparing the fingerprints in the current version. Can you please shed some light on it. 

Looking at the code I could not decipher whether multiple fingerprints (as in the ECFP's) for a molecule were generated and compared or just one as typical for the Morgan algorithm.

Thanks,
J

**Comment by connorcoley** [comment]
The model itself is a simple feedforward neural network model, which can theoretically take any numerical descriptor vector as input. The ```scripts/make_h5_file.py``` file contains a few different variations of Morgan fingerprint calculations or different lengths and boolean/integer values. We trained a few different models that each used a single one of these input representations. 

The code doesn't use any similarity calculations. However, to test different fingerprints or representations, all that needs to be done is preparing a different ```.h5``` file (matrix) by changing the ```mol_to_fp``` function in ```scripts/make_h5_file.py``` and setting the ```FP_len``` in the training script. For testing the retrained model, you would need to define the ```mol_to_fp``` function in ```nntrain_fingerprint.py``` to match the right input representation

**Comment by Jbru18** [comment]
Thanks for the explanation. I have very limited experience with the neural networks.
Does the model tolerate variable length fingerprints or do they all need to have the length ?
As the code does not use similarity how do different types of chemistry where no crossover from the reaction networks exist at lower complexity the scscore (eg. carbohydrate chemistry vs peptide or aromatic chemistry) ? 
Your article also mentioned that molecules frequently encountered as starting materials would have lower a scscore. How about reaction chains that frequently end with less structurally diverse molecules ? Would a bias towards a higher scscore be observed ?

**Comment by connorcoley** [comment]
This model architecture (standard feed forward neural network) does not tolerate variable length fingerprints. As a type of nonlinear regression, the model capacity is large enough that those different types of molecules can "exist" in different areas of the network. So certain parts will be more relevant for carbohydrate structures, others will be more relevant for aromatic compounds, etc. 

Motifs that appear more often in products (or at the end of a longer chain of reactions) will be biased toward a higher scscore, yes

**Comment by Jbru18** [comment]
Thanks for the insight!
How do I continue training of the existing reaxys model ? Do I need to start from a checkpoint ?

**Comment by connorcoley** [comment]
Yep! You'd want to restore from the checkpoint after initializing the saver, then continue on with training

**Comment by Jbru18** [comment]
Thanks Connor.

Is the latest checkpoint which includes the reaxys data set 'model.ckpt-10654' ? 
Can please let me know what the command line is for initializing the the saver and restarting the training.

Thanks,

J

**Comment by connorcoley** [comment]
Yes, that is the Reaxys-trained model. Restoring weights for testing begins on [this line](https://github.com/connorcoley/scscore/blob/master/scscore/nntrain_fingerprint.py#L319). To restore weights and continue training, you can set the ```checkpoint``` flag to ```ckpt-10654```.  You'll also want to delete line 319 of that file and unindent lines 320-327 so that the script restores weights even when it isn't testing or being interactive.

**Comment by tkram01** [comment]
I'm having trouble retraining the model. I get the following error with this command.  I am using tensorflow 0.12.0.

`python scscore/nntrain_fingerprint.py --train data/reaxys_limit10.txt`

`I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:3) -> (device: 3, name: Tesla K80, pci bus id: 0000:85:00.0)
Traceback (most recent call last):
  File "scscore/nntrain_fingerprint.py", line 98, in <module>
    mol_hiddens = tf.nn.relu(linearND(input_mol, hidden_size, scope="encoder0"))
  File "/cluster/home/kramer/scscore/utils/nn.py", line 23, in linearND
    target_shape = tf.concat([X_shape, [output_size]], 0)
  File "/cluster/home/kramer/anaconda3/envs/sdscore2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1076, in concat
    ).assert_is_compatible_with(tensor_shape.scalar())
  File "/cluster/home/kramer/anaconda3/envs/sdscore2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 756, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (2, 1) and () are incompatible`
